services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pakton-frontend-web
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - pakton-network

networks:
  pakton-network:
    driver: bridge