"""
Description:
Utility functions module that provides formatting, configuration, logging, and prompt templates for the Interrogator agent.

Author: Raptopoulos Petros [petrosrapto@gmail.com]
Date : 2025/03/10
"""

from .formatters import format_documents, format_conversation
from .prompts import INTERROGATION_SYSTEM_PROMPT, INTERROGATION_SYSTEM_PROMPT_FIRST_QUESTION, INTERROGATION_USER_PROMPT, INTERROGATION_USER_PROMPT_FIRST_QUESTION, LEGAL_CONCLUSION_WRITER_PROMPT, LEGAL_CONCLUSION_USER_PROMPT, LEGAL_REPORT_WRITER_PROMPT, LEGAL_REPORT_USER_PROMPT, ANSWER_REFINING_PROMPT, ANSWER_REFINING_USER_PROMPT, INTERROGATION_SYSTEM_PROMPT_FINAL_QUESTION, INTERROGATION_USER_PROMPT_FINAL_QUESTION

from .logging import logger
from .config import config

__all__ = [
    "format_documents",
    "format_conversation",
    "INTERROGATION_SYSTEM_PROMPT",
    "INTERROGATION_SYSTEM_PROMPT_FIRST_QUESTION",
    "INTERROGATION_USER_PROMPT",
    "INTERROGATION_USER_PROMPT_FIRST_QUESTION",
    "LEGAL_CONCLUSION_WRITER_PROMPT", 
    "LEGAL_CONCLUSION_USER_PROMPT",
    "LEGAL_REPORT_WRITER_PROMPT",
    "LEGAL_REPORT_USER_PROMPT",
    "ANSWER_REFINING_PROMPT",
    "ANSWER_REFINING_USER_PROMPT",
    "INTERROGATION_SYSTEM_PROMPT_FINAL_QUESTION",
    "INTERROGATION_USER_PROMPT_FINAL_QUESTION",
    "logger",
    "config"
]