#!/bin/bash

# Description: 
#     Helper script to create environment files on EC2 from GitHub Secrets.
#     This script should be run by GitHub Actions during deployment.
#     
# Author: Raptopoulos Petros [petrosrapto@gmail.com]
# Date  : 2025/11/24

set -e

ENV_DIR="$1"

if [ -z "$ENV_DIR" ]; then
    echo "Usage: $0 <env_directory>"
    exit 1
fi

mkdir -p "$ENV_DIR"

# API Environment
cat > "$ENV_DIR/api.env" << EOF
SUPABASE_URL=${DEV_SUPABASE_URL}
SUPABASE_JWT_SECRET=${DEV_SUPABASE_JWT_SECRET}
ENABLE_AUTHENTICATION=${DEV_ENABLE_AUTHENTICATION}
POSTGRES_DB=${DEV_POSTGRES_DB}
POSTGRES_USER=${DEV_POSTGRES_USER}
POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
EOF

# Archivist Environment
cat > "$ENV_DIR/archivist.env" << EOF
HUGGINGFACE_TOKEN=${DEV_HUGGINGFACE_TOKEN}
AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY}
AWS_REGION_NAME=${DEV_AWS_REGION_NAME}
EMBEDDINGS_API_KEY=${DEV_EMBEDDINGS_API_KEY}
OPENAI_API_KEY=${DEV_OPENAI_API_KEY}
TAVILY_API_KEY=${DEV_TAVILY_API_KEY}
LANGCHAIN_TRACING_V2=true
LANGCHAIN_PROJECT=${DEV_LANGCHAIN_PROJECT:-pakton-dev}
LANGCHAIN_API_KEY=${DEV_LANGCHAIN_API_KEY}
LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_VERBOSE=true
PINECONE_API_KEY=${DEV_PINECONE_API_KEY}
EOF

# Researcher Environment
cat > "$ENV_DIR/researcher.env" << EOF
HUGGINGFACE_TOKEN=${DEV_HUGGINGFACE_TOKEN}
AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY}
AWS_REGION_NAME=${DEV_AWS_REGION_NAME}
EMBEDDINGS_API_KEY=${DEV_EMBEDDINGS_API_KEY}
OPENAI_API_KEY=${DEV_OPENAI_API_KEY}
TAVILY_API_KEY=${DEV_TAVILY_API_KEY}
LANGCHAIN_TRACING_V2=true
LANGCHAIN_PROJECT=${DEV_LANGCHAIN_PROJECT:-pakton-dev}
LANGCHAIN_API_KEY=${DEV_LANGCHAIN_API_KEY}
LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_VERBOSE=true
PINECONE_API_KEY=${DEV_PINECONE_API_KEY}
GOOGLE_API_KEY=${DEV_GOOGLE_API_KEY}
EOF

# Interrogator Environment
cat > "$ENV_DIR/interrogator.env" << EOF
HUGGINGFACE_TOKEN=${DEV_HUGGINGFACE_TOKEN}
HUGGINGFACEHUB_API_TOKEN=${DEV_HUGGINGFACE_TOKEN}
AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY}
AWS_REGION_NAME=${DEV_AWS_REGION_NAME}
EMBEDDINGS_API_KEY=${DEV_EMBEDDINGS_API_KEY}
OPENAI_API_KEY=${DEV_OPENAI_API_KEY}
TAVILY_API_KEY=${DEV_TAVILY_API_KEY}
LANGCHAIN_TRACING_V2=true
LANGCHAIN_PROJECT=${DEV_LANGCHAIN_PROJECT:-pakton-dev}
LANGCHAIN_API_KEY=${DEV_LANGCHAIN_API_KEY}
LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_VERBOSE=true
PINECONE_API_KEY=${DEV_PINECONE_API_KEY}
GOOGLE_API_KEY=${DEV_GOOGLE_API_KEY}
EOF

# Frontend Environment
cat > "$ENV_DIR/frontend.env" << EOF
LOCAL_DEVELOPMENT=${DEV_LOCAL_DEVELOPMENT:-true}
NEXT_PUBLIC_SUPABASE_URL=${DEV_NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${DEV_NEXT_PUBLIC_SUPABASE_ANON_KEY}
NEXT_PUBLIC_SUPABASE_URL_DOCUMENTS=${DEV_NEXT_PUBLIC_SUPABASE_URL_DOCUMENTS}
NEXT_PUBLIC_SUPABASE_ANON_KEY_DOCUMENTS=${DEV_NEXT_PUBLIC_SUPABASE_ANON_KEY_DOCUMENTS}
NEXT_PUBLIC_GOOGLE_CLIENT_ID=${DEV_NEXT_PUBLIC_GOOGLE_CLIENT_ID}
EOF

# Secure the files
chmod 600 "$ENV_DIR"/*.env

echo "✅ Environment files created successfully in $ENV_DIR"
